### PR TITLE
Add Tomb of the Iron Medusa

### PR DESCRIPTION
**Pull request by DrMcCoy**
This adds a statblock compendium for the module Tomb of the Iron Medusa (PZO9530). It's just 6 statblocks, but I'm currently running this module for one of my groups, so I might as well.

The module comes with a new monster, a Nemhain, but since then, it got collected in Bestiary 5, so I'm not adding it again here.

Creating the db file, I cheated a bit. I basically just ripped apart one of yours, copied one entry of that, removed the flags structure and used that as a template for my entries, generating a random ID each time. I.e. I didn't export a compendium from Foundry. It still works, so I hope that okay.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
@baileymh Is this in general something you'd want?

I could also do that for the modules I've run previously with that group, Academy of Secrets (PZO9531) and The Puzzle Box (which came with the Kingmaker videogame); I've still got textfiles of the statblocks around I've used to import the NPCs.

What about modules that were originally using D&D 3.5 rules, would you be interested in a more or less direct conversion of the statblocks into Pathfinder like that? There's two additionally modules I've run where I did that, that I could put a little more work into for a PR here.

If, however, you don't actually want this, which is of course fine, I know I don't need to bother. :)

**Comment by baileymh** [comment]
Sorry, been a little busy irl. 

Sure! If there are others you'd like to take the time and effort to add, I'd be more than happy to merge them! I do request you try to stay consistent with my naming convention, so that people can more easily search for particular CR/Classes.

**Comment by DrMcCoy** [comment]
Can you give an example? I'm not quite sure what you mean. I don't think I've done any particular editorializing, everything is directly from the module

**Comment by baileymh** [comment]
This is just for naming of the NPC within Foundry.
I include CR for monsters, and class and level for npcs. 

Not a huge deal, and you don't need to go through and reedit things, but it's helpful for people who use Quick Insert or Search Anywhere (and also helps reduce duplicate names - he says with an image that has duplicates lol).
image

**Comment by DrMcCoy** [comment]
Oh, okay, yeah, I didn't see that, because I had only looked at the adventure path compendiums in detail, and there that isn't done.

I'll keep that in mind for the future!

**Pull request merged**
